services:
    app:
        build:
            context: .
            dockerfile: docker-config/Dockerfile
        image: exchange-crypto
        container_name: exchange-crypto-${PREFIX_CONTAINER_NAME:-dev}
        restart: unless-stopped
        working_dir: /var/www/src
        volumes:
            - .:/var/www
            - ./.bash_history:/home/node/.bash_history:rw
            - ./tmp/app/:/home/node/.npm/
            - /etc/localtime:/etc/localtime:ro
        depends_on:
            - nginx
        networks:
            - exchange-crypto
        ports:
            - ${PORT:-3002}:${PORT:-3002}
        env_file:
            - .env
        environment:
            NODE_ENV: ${NODE_ENV:-production}
            STATUS_APP: ${STATUS_APP:-false}
            STATUS_LOGIN: ${STATUS_LOGIN:-true}
            PORT: ${PORT:-3002}
        command: ["sleep", "infinity"]

    nginx:
        image: nginx:latest
        container_name: exchange-crypto-nginx-${PREFIX_CONTAINER_NAME:-dev}
        restart: unless-stopped
        ports:
            - ${NGINX_PORT:-8002}:80
            - ${NGINX_PORT_SSL:-445}:443
        volumes:
            - .:/var/www
            - ./docker-config/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - exchange-crypto

networks:
    exchange-crypto:
        driver: bridge
        name: exchange-crypto-${PREFIX_CONTAINER_NAME:-dev}
