services:
    app:
        build:
            context: .
            dockerfile: docker-config/Dockerfile
        image: exchange-crypto
        container_name: exchange-crypto-${PREFIX_CONTAINER_NAME}
        restart: unless-stopped
        working_dir: /var/www/src
        volumes:
            - .:/var/www
            # - ./.bash_history:/home/${USER}/.bash_history
            # - ${SSH_PATH}:/home/${USER}/.ssh:ro
            - ./.bash_history:/home/node/.bash_history:rw
            - ${SSH_PATH}:/home/node/.ssh:ro
            - ${GITCONFIG_PATH}:/home/${USER}/.gitconfig:ro
            - ./tmp/app/:/home/node/.npm/
            - /etc/localtime:/etc/localtime:ro
        depends_on:
            - nginx
        networks:
            - exchange-crypto
        ports:
            - ${PORT}:${PORT}
        env_file:
            - .env
        command: ["sleep", "infinity"]

    nginx:
        image: nginx:latest
        container_name: exchange-crypto-nginx-${PREFIX_CONTAINER_NAME}
        restart: unless-stopped
        ports:
            - ${NGINX_PORT}:80
            - ${NGINX_PORT_SSL}:443
        volumes:
            - .:/var/www
            - ./docker-config/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - exchange-crypto

networks:
    exchange-crypto:
        driver: bridge
        name: exchange-crypto-${PREFIX_CONTAINER_NAME}
